server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mybatis-learn
    username: root
    password: admin



mybatis:
  mapper-locations: classpath:mapper/*.xml
  typeAliasesPackage: com.liuhongyin.mybatislearn.model